/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComputeRouteImport } from './routes/compute'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as RoadmapRouteImport } from './routes/roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/datasets': typeof DatasetsRoute
  '/decisions': typeof DecisionsRoute
  '/documentation': typeof DocumentationRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/models': typeof ModelsRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/datasets': typeof DatasetsRoute
  '/decisions': typeof DecisionsRoute
  '/documentation': typeof DocumentationRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/models': typeof ModelsRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/datasets': typeof DatasetsRoute
  '/decisions': typeof DecisionsRoute
  '/documentation': typeof DocumentationRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/models': typeof ModelsRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compute'
    | '/datasets'
    | '/decisions'
    | '/documentation'
    | '/evaluation'
    | '/experiments'
    | '/models'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compute'
    | '/datasets'
    | '/decisions'
    | '/documentation'
    | '/evaluation'
    | '/experiments'
    | '/models'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/compute'
    | '/datasets'
    | '/decisions'
    | '/documentation'
    | '/evaluation'
    | '/experiments'
    | '/models'
    | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComputeRoute: typeof ComputeRoute
  DatasetsRoute: typeof DatasetsRoute
  DecisionsRoute: typeof DecisionsRoute
  DocumentationRoute: typeof DocumentationRoute
  EvaluationRoute: typeof EvaluationRoute
  ExperimentsRoute: typeof ExperimentsRoute
  ModelsRoute: typeof ModelsRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComputeRoute: ComputeRoute,
  DatasetsRoute: DatasetsRoute,
  DecisionsRoute: DecisionsRoute,
  DocumentationRoute: DocumentationRoute,
  EvaluationRoute: EvaluationRoute,
  ExperimentsRoute: ExperimentsRoute,
  ModelsRoute: ModelsRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
