"""Deterministic research corpora for tokenizer analysis.

Two *disjoint* artifacts are produced by this module:

1. ``train.txt`` — text used to **train** a tokenizer. It is generated deterministically
   from small curated word lists per language plus the Project 001 English synthetic
   corpus generator.
2. ``eval.jsonl`` — a hand-written **evaluation fixture** of representative examples
   (one JSON object per line: ``id``, ``lang``, ``category``, ``text``).

CRITICAL LIMITATIONS — read before quoting any number produced with this corpus:

* This is an **evaluation fixture, not a training corpus**. It contains a few hundred
  short strings, not millions of documents.
* It does **not** represent the statistical distribution of any language. It is a
  hand-written probe set designed to expose tokenizer *behaviour* (how scripts, digits,
  punctuation and mixing are handled), not to measure real-world quality.
* Training text is generated from small word lists that **overlap** with the words used
  in the evaluation examples. Compression numbers measured on this fixture are therefore
  *optimistic* and are only comparable between tokenizers measured on the same fixture.
* No web scraping, no private data, no copyrighted text. Every string here is written by
  the project authors or generated by our own deterministic code.
"""

from __future__ import annotations

import hashlib
import json
import random
from collections.abc import Iterable, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path

from ..data.synthetic import generate_corpus

CORPUS_ID = "indic-eval"
CORPUS_VERSION = "v1"
SCHEMA_VERSION = "1.0"

# ---------------------------------------------------------------------------
# Languages under study (ISO-639-1/3 code -> display name)
# ---------------------------------------------------------------------------
LANGUAGES: dict[str, str] = {
    "en": "English",
    "hi": "Hindi",
    "hi-en": "Hinglish (code-mixed Hindi-English)",
    "bn": "Bengali",
    "mr": "Marathi",
    "gu": "Gujarati",
    "ta": "Tamil",
    "te": "Telugu",
    "kn": "Kannada",
    "ml": "Malayalam",
    "pa": "Punjabi",
    "or": "Odia",
    "as": "Assamese",
    "ur": "Urdu",
}

# Non-language probe categories (orthography / formatting stress tests).
CATEGORIES: dict[str, str] = {
    "numbers": "Integers, grouped numbers, Indic digits",
    "dates": "Date formats including Indic digits and month names",
    "decimals": "Decimals, currency, percentages",
    "math": "Mathematical and ML notation",
    "punctuation": "Punctuation, quotes, dashes, brackets",
    "urls": "URLs as plain text",
    "tech_terms": "English technical vocabulary",
    "code_mixed_tech": "Technical code-mixing (English tech terms inside Indic sentences)",
    "unicode_marks": "Emoji, combining marks, conjuncts, repeated characters",
}

# ---------------------------------------------------------------------------
# Evaluation fixture: hand-written representative examples.
# These strings are distinct from the generated training text, but they reuse
# common words from WORD_BANK (see module docstring).
# ---------------------------------------------------------------------------
EXAMPLE_BANK: dict[str, list[str]] = {
    "en": [
        "The model trains on a small local corpus.",
        "Tokenizer quality affects cost, context length and accuracy.",
        "We evaluate every checkpoint before release.",
        "The weather is pleasant today.",
        "Please send the report before Friday.",
        "She is reading a book about engines.",
        "Our team works on language models for Indian languages.",
    ],
    "hi": [
        "यह एक छोटा उदाहरण वाक्य है।",
        "मैं स्कूल जा रहा हूँ।",
        "आज मौसम बहुत अच्छा है।",
        "भारत की राजधानी नई दिल्ली है।",
        "मुझे किताब पढ़ना पसंद है।",
        "बाज़ार में सब्ज़ियाँ मिलती हैं।",
        "विद्यार्थी परीक्षा की तैयारी कर रहे हैं।",
        "कंप्यूटर विज्ञान एक महत्वपूर्ण विषय है।",
    ],
    "hi-en": [
        "Main aaj office nahi ja raha, thoda kaam ghar se kar lunga.",
        "Yeh model ka output bilkul sahi hai.",
        "Kal meeting me dataset ke baare me discuss karenge.",
        "Please mujhe ek chai dena, bina sugar ke.",
        "Training loss thoda high hai, learning rate kam karte hain.",
        "Aaj traffic bahut tha, isliye late ho gaya.",
    ],
    "bn": [
        "এটি একটি ছোট উদাহরণ বাক্য।",
        "আজ আবহাওয়া খুব ভালো।",
        "আমি স্কুলে যাচ্ছি।",
        "ভারতের রাজধানী নয়াদিল্লি।",
        "তুমি কেমন আছো?",
        "আমাদের কাজ শেষ হয়েছে।",
        "বইটি টেবিলের উপর আছে।",
        "সে বাজার থেকে ফিরেছে।",
    ],
    "mr": [
        "हे एक छोटे उदाहरण वाक्य आहे.",
        "मी शाळेत जात आहे.",
        "आज हवामान खूप छान आहे.",
        "भारताची राजधानी नवी दिल्ली आहे.",
        "तू कसा आहेस?",
        "मला पुस्तक वाचायला आवडते.",
        "पाणी खूप थंड आहे.",
        "आमचे काम पूर्ण झाले.",
    ],
    "gu": [
        "આ એક નાનું ઉદાહરણ વાક્ય છે.",
        "હું શાળાએ જાઉં છું.",
        "આજે હવામાન ખૂબ સારું છે.",
        "ભારતની રાજધાની નવી દિલ્હી છે.",
        "તમે કેમ છો?",
        "મને પુસ્તક વાંચવું ગમે છે.",
        "પાણી ખૂબ ઠંડું છે.",
        "અમારું કામ પૂરું થયું.",
    ],
    "ta": [
        "இது ஒரு சிறிய எடுத்துக்காட்டு வாக்கியம்.",
        "நான் பள்ளிக்கு செல்கிறேன்.",
        "இன்று வானிலை மிகவும் நன்றாக உள்ளது.",
        "இந்தியாவின் தலைநகரம் புது தில்லி.",
        "நீ எப்படி இருக்கிறாய்?",
        "எனக்கு புத்தகம் படிக்க பிடிக்கும்.",
        "தண்ணீர் மிகவும் குளிராக உள்ளது.",
        "எங்கள் வேலை முடிந்தது.",
    ],
    "te": [
        "ఇది ఒక చిన్న ఉదాహరణ వాక్యం.",
        "నేను బడికి వెళ్తున్నాను.",
        "ఈ రోజు వాతావరణం చాలా బాగుంది.",
        "భారతదేశ రాజధాని న్యూఢిల్లీ.",
        "మీరు ఎలా ఉన్నారు?",
        "నాకు పుస్తకం చదవడం ఇష్టం.",
        "నీళ్లు చాలా చల్లగా ఉన్నాయి.",
        "మా పని పూర్తయింది.",
    ],
    "kn": [
        "ಇದು ಒಂದು ಸಣ್ಣ ಉದಾಹರಣೆ ವಾಕ್ಯ.",
        "ನಾನು ಶಾಲೆಗೆ ಹೋಗುತ್ತಿದ್ದೇನೆ.",
        "ಇಂದು ಹವಾಮಾನ ತುಂಬಾ ಚೆನ್ನಾಗಿದೆ.",
        "ಭಾರತದ ರಾಜಧಾನಿ ನವದೆಹಲಿ.",
        "ನೀವು ಹೇಗಿದ್ದೀರಿ?",
        "ನನಗೆ ಪುಸ್ತಕ ಓದಲು ಇಷ್ಟ.",
        "ನೀರು ತುಂಬಾ ತಣ್ಣಗಿದೆ.",
        "ನಮ್ಮ ಕೆಲಸ ಮುಗಿದಿದೆ.",
    ],
    "ml": [
        "ഇത് ഒരു ചെറിയ ഉദാഹരണ വാക്യം ആണ്.",
        "ഞാൻ സ്കൂളിൽ പോകുന്നു.",
        "ഇന്ന് കാലാവസ്ഥ വളരെ നല്ലതാണ്.",
        "ഇന്ത്യയുടെ തലസ്ഥാനം ന്യൂഡൽഹി ആണ്.",
        "നിങ്ങൾക്ക് സുഖമാണോ?",
        "എനിക്ക് പുസ്തകം വായിക്കാൻ ഇഷ്ടമാണ്.",
        "വെള്ളം വളരെ തണുപ്പാണ്.",
        "ഞങ്ങളുടെ ജോലി പൂർത്തിയായി.",
    ],
    "pa": [
        "ਇਹ ਇੱਕ ਛੋਟੀ ਉਦਾਹਰਣ ਵਾਕ ਹੈ।",
        "ਮੈਂ ਸਕੂਲ ਜਾ ਰਿਹਾ ਹਾਂ।",
        "ਅੱਜ ਮੌਸਮ ਬਹੁਤ ਵਧੀਆ ਹੈ।",
        "ਭਾਰਤ ਦੀ ਰਾਜਧਾਨੀ ਨਵੀਂ ਦਿੱਲੀ ਹੈ।",
        "ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?",
        "ਮੈਨੂੰ ਕਿਤਾਬ ਪੜ੍ਹਨਾ ਪਸੰਦ ਹੈ।",
        "ਪਾਣੀ ਬਹੁਤ ਠੰਡਾ ਹੈ।",
        "ਸਾਡਾ ਕੰਮ ਪੂਰਾ ਹੋ ਗਿਆ।",
    ],
    "or": [
        "ଏହା ଏକ ଛୋଟ ଉଦାହରଣ ବାକ୍ୟ।",
        "ମୁଁ ବିଦ୍ୟାଳୟକୁ ଯାଉଛି।",
        "ଆଜି ପାଗ ବହୁତ ଭଲ।",
        "ଭାରତର ରାଜଧାନୀ ନୂଆଦିଲ୍ଲୀ।",
        "ତୁମେ କେମିତି ଅଛ?",
        "ମୋତେ ବହି ପଢ଼ିବାକୁ ଭଲ ଲାଗେ।",
        "ପାଣି ବହୁତ ଥଣ୍ଡା।",
        "ଆମର କାମ ଶେଷ ହେଲା।",
    ],
    "as": [
        "এইটো এটা সৰু উদাহৰণ বাক্য।",
        "মই বিদ্যালয়লৈ গৈ আছোঁ।",
        "আজি বতৰ বৰ ভাল।",
        "ভাৰতৰ ৰাজধানী নতুন দিল্লী।",
        "তুমি কেনে আছা?",
        "মোৰ কিতাপ পঢ়িবলৈ ভাল লাগে।",
        "পানী বৰ ঠাণ্ডা।",
        "আমাৰ কাম শেষ হ’ল।",
    ],
    "ur": [
        "یہ ایک چھوٹی مثال ہے۔",
        "میں اسکول جا رہا ہوں۔",
        "آج موسم بہت اچھا ہے۔",
        "بھارت کا دارالحکومت نئی دہلی ہے۔",
        "آپ کیسے ہیں؟",
        "مجھے کتاب پڑھنا پسند ہے۔",
        "پانی بہت ٹھنڈا ہے۔",
        "ہمارا کام مکمل ہو گیا۔",
    ],
}

CATEGORY_BANK: dict[str, list[str]] = {
    "numbers": [
        "1234567",
        "42",
        "1,234,567",
        "पांच सौ बीस",
        "১২৩৪৫",
        "௧௨௩",
        "2026",
        "0",
        "1 000 000",
    ],
    "dates": [
        "2026-09-10",
        "10/09/2026",
        "10 September 2026",
        "१० सितंबर २০२६",
        "সেপ্টেম্বর ২০২৬",
        "Sep 10, 2026",
        "2026-09-10T09:10:27Z",
    ],
    "decimals": [
        "3.14159",
        "0.001",
        "₹1,299.50",
        "12.5%",
        "1e-6",
        "-273.15",
        "९९.९९",
    ],
    "math": [
        "x^2 + y^2 = z^2",
        "loss = -log p(y|x)",
        "2 × (3 + 4) = 14",
        "a₁ + a₂ = b",
        "∇·E = ρ/ε₀",
        "attention(Q, K, V) = softmax(QKᵀ/√d) V",
        "f(x) = ∫ g(t) dt",
    ],
    "punctuation": [
        "Hello, world! How are you? (fine, thanks) — really?",
        "‘single’ and “double” quotes; semi-colons: colons.",
        "Wait… what?!  Multiple   spaces    here.",
        "key: value, list: [a, b, c], tuple: (1, 2)",
        "email: researcher@example.org",
        "हिंदी — विराम चिह्न? (हाँ!)",
    ],
    "urls": [
        "https://example.com/docs/tokenizer",
        "www.example.org",
        "http://localhost:8000/api/v1/items?id=42",
        "https://hi.wikipedia.org/wiki/हिन्दी",
        "git+ssh://git@github.com/dfgtghu556-ops/frontier-ai.git",
    ],
    "tech_terms": [
        "transformer",
        "gradient descent",
        "attention mechanism",
        "tokenizer vocabulary",
        "mixed precision training",
        "kv cache",
        "checkpoint",
        "embedding matrix",
        "learning rate scheduler",
        "cross entropy loss",
    ],
    "code_mixed_tech": [
        "model को train करना है",
        "dataset बहुत बड़ा है",
        "learning rate कम करें",
        "tokenizer vocab size बढ़ाओ",
        "GPU memory कम पड़ रही है",
        "for batch in dataloader: loss.backward()",
        "def train(model): optimizer.step()",
        "আমাদের model টা retrain করতে হবে",
    ],
    "unicode_marks": [
        "नमस्ते 🙏",
        "launch 🚀🚀",
        "hello 😀",
        "👨‍👩‍👧 family emoji with ZWJ",
        "soooo good",
        "वाहहहह",
        "क्षमा",  # Devanagari conjunct
        "हिन्दी",  # combining vowel sign + virama
        "é combining accent vs é precomposed",
        "আমি",  # Bengali with dependent vowel
        "👍🏽 skin-tone modifier",
    ],
}

# ---------------------------------------------------------------------------
# Word banks used ONLY to generate the *training* text. Small on purpose.
# ---------------------------------------------------------------------------
WORD_BANK: dict[str, list[str]] = {
    "en": ["model", "data", "train", "loss", "token", "school", "water", "book", "market", "report",
           "team", "weather", "student", "computer", "science", "city", "road", "friend"],
    "hi": ["मॉडल", "डेटा", "स्कूल", "पानी", "किताब", "बाज़ार", "रिपोर्ट", "मौसम", "विद्यार्थी", "शहर",
           "सड़क", "दोस्त", "कंप्यूटर", "विज्ञान", "काम"],
    "hi-en": ["model", "dataset", "training", "loss", "learning", "rate", "office", "meeting", "traffic",
              "late", "kam", "kar", "hai", "bahut", "accha"],
    "bn": ["মডেল", "তথ্য", "স্কুল", "জল", "বই", "বাজার", "রিপোর্ট", "আবহাওয়া", "ছাত্র", "শহর",
           "রাস্তা", "বন্ধু", "কম্পিউটার", "বিজ্ঞান", "কাজ"],
    "mr": ["मॉडेल", "डेटा", "शाळा", "पाणी", "पुस्तक", "बाजार", "अहवाल", "हवामान", "विद्यार्थी", "शहर",
           "रस्ता", "मित्र", "संगणक", "विज्ञान", "काम"],
    "gu": ["મોડલ", "ડેટા", "શાળા", "પાણી", "પુસ્તક", "બજાર", "અહેવાલ", "હવામાન", "વિદ્યાર્થી", "શહેર",
           "રસ્તો", "મિત્ર", "કમ્પ્યુટર", "વિજ્ઞાન", "કામ"],
    "ta": ["மாதிரி", "தரவு", "பள்ளி", "நீர்", "புத்தகம்", "சந்தை", "அறிக்கை", "வானிலை", "மாணவர்", "நகரம்",
           "சாலை", "நண்பர்", "கணினி", "அறிவியல்", "வேலை"],
    "te": ["నమూనా", "డేటా", "బడి", "నీళ్లు", "పుస్తకం", "మార్కెట్", "నివేదిక", "వాతావరణం", "విద్యార్థి", "నగరం",
           "రోడ్డు", "స్నేహితుడు", "కంప్యూటర్", "శాస్త్రం", "పని"],
    "kn": ["ಮಾದರಿ", "ಡೇಟಾ", "ಶಾಲೆ", "ನೀರು", "ಪುಸ್ತಕ", "ಮಾರುಕಟ್ಟೆ", "ವರದಿ", "ಹವಾಮಾನ", "ವಿದ್ಯಾರ್ಥಿ", "ನಗರ",
           "ರಸ್ತೆ", "ಗೆಳೆಯ", "ಕಂಪ್ಯೂಟರ್", "ವಿಜ್ಞಾನ", "ಕೆಲಸ"],
    "ml": ["മാതൃക", "ഡാറ്റ", "സ്കൂൾ", "വെള്ളം", "പുസ്തകം", "ചന്ത", "റിപ്പോർട്ട്", "കാലാവസ്ഥ", "വിദ്യാർത്ഥി",
           "നഗരം", "റോഡ്", "സുഹൃത്ത്", "കമ്പ്യൂട്ടർ", "ശാസ്ത്രം", "ജോലി"],
    "pa": ["ਮਾਡਲ", "ਡਾਟਾ", "ਸਕੂਲ", "ਪਾਣੀ", "ਕਿਤਾਬ", "ਬਾਜ਼ਾਰ", "ਰਿਪੋਰਟ", "ਮੌਸਮ", "ਵਿਦਿਆਰਥੀ", "ਸ਼ਹਿਰ",
           "ਸੜਕ", "ਦੋਸਤ", "ਕੰਪਿਊਟਰ", "ਵਿਗਿਆਨ", "ਕੰਮ"],
    "or": ["ମଡେଲ", "ତଥ୍ୟ", "ବିଦ୍ୟାଳୟ", "ପାଣି", "ବହି", "ବଜାର", "ରିପୋର୍ଟ", "ପାଗ", "ଛାତ୍ର", "ସହର",
           "ରାସ୍ତା", "ବନ୍ଧୁ", "କମ୍ପ୍ୟୁଟର", "ବିଜ୍ଞାନ", "କାମ"],
    "as": ["মডেল", "তথ্য", "বিদ্যালয়", "পানী", "কিতাপ", "বজাৰ", "প্ৰতিবেদন", "বতৰ", "ছাত্ৰ", "নগৰ",
           "পথ", "বন্ধু", "কম্পিউটাৰ", "বিজ্ঞান", "কাম"],
    "ur": ["ماڈل", "ڈیٹا", "اسکول", "پانی", "کتاب", "بازار", "رپورٹ", "موسم", "طالب علم", "شہر",
           "سڑک", "دوست", "کمپیوٹر", "سائنس", "کام"],
}

# English technical lines used in training text (disjoint from eval strings).
_TECH_LINES = [
    "We train a decoder-only transformer with gradient accumulation.",
    "The optimizer uses AdamW with cosine decay and warmup.",
    "Validation perplexity is reported every eval interval.",
    "Mixed precision keeps master weights in float32.",
    "Checkpoints store weights, optimizer state and the config.",
    "Throughput is measured in tokens per second.",
    "The scheduler decays the learning rate to ten percent.",
    "Batches are sampled as random contiguous windows.",
]

_CODE_LINES = [
    "def train_step(model, batch):",
    "    loss = model(batch.x, targets=batch.y).loss",
    "    loss.backward()",
    "    optimizer.step()",
    "for epoch in range(num_epochs):",
    "    for batch in loader:",
    "        train_step(model, batch)",
    "import torch",
    "x = torch.tensor([1, 2, 3])",
    "model.eval()",
]


@dataclass(frozen=True)
class Example:
    """One evaluation probe. ``category`` is ``"sentence"`` for language examples."""

    id: str
    lang: str
    category: str
    text: str


@dataclass(frozen=True)
class CorpusManifest:
    """Machine-readable description of a written corpus directory."""

    corpus_id: str
    corpus_version: str
    schema_version: str
    seed: int
    n_examples: int
    languages: list[str]
    categories: list[str]
    train_chars: int
    train_lines: int
    train_sha256: str
    eval_sha256: str

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> CorpusManifest:
        return cls(**data)


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path: str | Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build_examples() -> list[Example]:
    """The evaluation fixture: language sentences + orthography probe categories."""
    examples: list[Example] = []
    for lang, sentences in EXAMPLE_BANK.items():
        for i, text in enumerate(sentences, start=1):
            examples.append(Example(id=f"{lang}-{i:03d}", lang=lang, category="sentence", text=text))
    for category, items in CATEGORY_BANK.items():
        for i, text in enumerate(items, start=1):
            examples.append(Example(id=f"{category}-{i:03d}", lang="mixed", category=category, text=text))
    return examples


def _sentences_for_language(lang: str, words: Sequence[str], rng: random.Random, count: int) -> list[str]:
    """Build simple, grammatical-ish sentences from a word bank (fixture only)."""
    out: list[str] = []
    for _ in range(count):
        a, b, c = (rng.choice(words) for _ in range(3))
        style = rng.randint(0, 2)
        if style == 0:
            line = f"{a} {b} {c}."
        elif style == 1:
            line = f"{a} {b}, {c} {rng.choice(words)}?"
        else:
            line = f"{a} {rng.choice(words)} {b}; {c}."
        out.append(line)
    return out


def generate_train_text(
    seed: int = 1337,
    sentences_per_language: int = 60,
    english_chars: int = 40_000,
) -> str:
    """Deterministic training text for tokenizer fitting.

    Composition: generated sentences from each language's word bank, numeric/date/math
    variants, English technical lines, code snippets, and the Project 001 synthetic
    English corpus. Deterministic for a fixed seed.
    """
    rng = random.Random(seed)
    blocks: list[str] = []

    for lang, words in WORD_BANK.items():
        blocks.extend(_sentences_for_language(lang, words, rng, sentences_per_language))

    numbers: list[str] = []
    for _ in range(200):
        n = rng.randint(0, 9_999_999)
        numbers.append(rng.choice([str(n), f"{n:,}", f"{n / 100:.2f}", f"{n}%"]))
    for _ in range(120):
        y = rng.randint(1990, 2035)
        m = rng.randint(1, 12)
        d = rng.randint(1, 28)
        numbers.append(rng.choice([f"{y:04d}-{m:02d}-{d:02d}", f"{d:02d}/{m:02d}/{y:04d}", f"{d} March {y}"]))
    for _ in range(80):
        a, b = rng.randint(1, 999), rng.randint(1, 999)
        numbers.append(f"x = {a} + {b} * 2  # {a + b * 2}")
    blocks.extend(numbers)

    blocks.extend(_TECH_LINES * 12)
    blocks.extend(_CODE_LINES * 6)
    blocks.append(generate_corpus(target_chars=english_chars, seed=seed))

    return "\n".join(blocks) + "\n"


def write_corpus(
    out_dir: str | Path,
    seed: int = 1337,
    sentences_per_language: int = 60,
    english_chars: int = 40_000,
) -> CorpusManifest:
    """Write ``train.txt``, ``eval.jsonl`` and ``manifest.json`` into ``out_dir``."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    train_text = generate_train_text(
        seed=seed, sentences_per_language=sentences_per_language, english_chars=english_chars
    )
    examples = build_examples()

    train_path = out / "train.txt"
    eval_path = out / "eval.jsonl"
    manifest_path = out / "manifest.json"

    train_path.write_text(train_text, encoding="utf-8")
    eval_path.write_text(
        "\n".join(json.dumps(asdict(ex), ensure_ascii=False) for ex in examples) + "\n",
        encoding="utf-8",
    )

    manifest = CorpusManifest(
        corpus_id=CORPUS_ID,
        corpus_version=CORPUS_VERSION,
        schema_version=SCHEMA_VERSION,
        seed=seed,
        n_examples=len(examples),
        languages=sorted(EXAMPLE_BANK),
        categories=sorted(CATEGORY_BANK),
        train_chars=len(train_text),
        train_lines=train_text.count("\n"),
        train_sha256=sha256_text(train_text),
        eval_sha256=sha256_file(eval_path),
    )
    manifest_path.write_text(json.dumps(manifest.to_dict(), indent=2) + "\n", encoding="utf-8")
    return manifest


def load_corpus(corpus_dir: str | Path) -> tuple[list[Example], CorpusManifest]:
    """Read a corpus directory written by :func:`write_corpus`."""
    base = Path(corpus_dir)
    manifest_path = base / "manifest.json"
    eval_path = base / "eval.jsonl"
    if not manifest_path.exists():
        raise FileNotFoundError(f"corpus manifest not found: {manifest_path} (run the prepare-corpus CLI)")
    if not eval_path.exists():
        raise FileNotFoundError(f"evaluation fixture not found: {eval_path}")

    manifest = CorpusManifest.from_dict(json.loads(manifest_path.read_text(encoding="utf-8")))
    examples = [
        Example(**json.loads(line))
        for line in eval_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]

    # fail loudly instead of silently benchmarking against a mutated fixture
    actual = sha256_file(eval_path)
    if actual != manifest.eval_sha256:
        raise ValueError(
            f"evaluation fixture hash mismatch: manifest says {manifest.eval_sha256[:12]}…, "
            f"file is {actual[:12]}… — the corpus was modified after it was written"
        )
    return examples, manifest


def examples_by_language(examples: Iterable[Example]) -> dict[str, list[Example]]:
    out: dict[str, list[Example]] = {}
    for ex in examples:
        out.setdefault(ex.lang, []).append(ex)
    return out


def examples_by_category(examples: Iterable[Example]) -> dict[str, list[Example]]:
    out: dict[str, list[Example]] = {}
    for ex in examples:
        out.setdefault(ex.category, []).append(ex)
    return out
