#!/usr/bin/env python3
"""Write the deterministic tokenizer research corpus (training text + evaluation fixture).

The corpus is generated by our own code — nothing is downloaded and nothing is copied
from a third party. It is an **evaluation fixture**, not a training corpus.

Example
-------
    python scripts/tokenizer_prepare_corpus.py --out data/tokenizer/indic-v1
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from frontier_ai.tokenization.corpus import (  # noqa: E402
    CATEGORIES,
    LANGUAGES,
    write_corpus,
)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--out", default="data/tokenizer/indic-v1", help="corpus output directory")
    p.add_argument("--seed", type=int, default=1337, help="generation seed")
    p.add_argument(
        "--sentences-per-language", type=int, default=60, help="generated training sentences per language"
    )
    p.add_argument(
        "--english-chars", type=int, default=40_000, help="chars of synthetic English training text"
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    manifest = write_corpus(
        args.out,
        seed=args.seed,
        sentences_per_language=args.sentences_per_language,
        english_chars=args.english_chars,
    )
    print(
        f"[corpus] wrote {args.out}/train.txt "
        f"({manifest.train_chars:,} chars, {manifest.train_lines:,} lines) "
        f"and eval.jsonl ({manifest.n_examples} examples)"
    )
    print(f"[corpus] languages={len(LANGUAGES)} probe_categories={len(CATEGORIES)} seed={manifest.seed}")
    print(f"[corpus] train_sha256={manifest.train_sha256[:16]}… eval_sha256={manifest.eval_sha256[:16]}…")
    print(
        "[corpus] WARNING: this is a hand-written probe fixture. It does NOT represent the "
        "statistical distribution of any language."
    )
    if args.out:
        print(json.dumps({"corpus_dir": str(Path(args.out)), **manifest.to_dict()}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
